server:
  port: 8761 # default port number where service discovery runs

spring:
  application:
    name: SERVICE-DISCOVERY

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
