
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# zipkin configuration will trace 100% logs
management:
  tracing:
    sampling:
      probability: 1.0


